_extends: .github
repository:
  name: eslint-config-hal
  description: Shareable config for producers and consumers of HAL APIs
  homepage: 'https://npm.im/@form8ion/eslint-config-hal'
  private: false
